/**
 * Applies the latest public favicon state generated by GitHub Actions.
 * No API calls happen in the browser, so no secret is exposed client-side.
 */
(function () {
  'use strict';

  function upsertFavicon(href, type) {
    var selector = 'link[rel~="icon"][data-dynamic-rank]';
    var link = document.querySelector(selector);

    if (!link) {
      link = document.createElement('link');
      link.rel = 'icon';
      link.setAttribute('data-dynamic-rank', '');
      document.head.appendChild(link);
    }

    if (type) {
      link.type = type;
    }

    link.href = href;
  }

  var cfg = window.__VALORANT_FAVICON__;
  if (!cfg || typeof cfg !== 'object') {
    return;
  }

  if (cfg.defaultIconHref) {
    upsertFavicon(cfg.defaultIconHref, 'image/svg+xml');
  }

  if (cfg.iconHref) {
    upsertFavicon(cfg.iconHref, 'image/png');
  }
})();
