// games/clicker/balance.js
// Centralized balancing constants — edit here to rebalance the entire game.

const BALANCE = {
    // === ZONES ===
    zones: [
        { name: "Coal Mine",      oreName: "Coal Ore",     color: "#555",    sellRate: 1 },
        { name: "Copper Cave",    oreName: "Copper Ore",   color: "#b87333", sellRate: 4 },
        { name: "Iron Depths",    oreName: "Iron Ore",     color: "#a19d94", sellRate: 12 },
        { name: "Gold Shaft",     oreName: "Gold Ore",     color: "#ffd700", sellRate: 30 },
        { name: "Ruby Core",      oreName: "Ruby Ore",     color: "#e0115f", sellRate: 70 },
        { name: "Emerald Pit",    oreName: "Emerald Ore",  color: "#50c878", sellRate: 150 },
        { name: "Diamond Hollow", oreName: "Diamond Ore",  color: "#b9f2ff", sellRate: 300 },
        { name: "Void Chasm",     oreName: "Void Ore",     color: "#301934", sellRate: 600 }
    ],

    // === PICKAXE ===
    maxPickaxeLevel: 200,
    levelsPerTier: 25,
    // Gold cost = pickaxeGoldBase * goldExponent ^ level  (smooth global curve, no tier resets)
    pickaxeGoldBase: 10,
    pickaxeGoldExponent: 1.06,
    // Ore cost = baseOre * exponent ^ (level % levelsPerTier)  (resets at boundary levels)
    pickaxeOreBaseCost: 10,
    pickaxeOreExponent: 1.05,

    // === MINERS ===
    // Ores per second generated by each miner type
    minerYields:        { goblin: 0.2, dwarf: 0.4, drill: 1.0 },
    // Miner gold cost = zoneSellRate * baseMultiplier * costExponent ^ owned
    minerBaseMultipliers: { goblin: 300, dwarf: 1500, drill: 7500 },
    minerCostExponent: 1.5,

    // === ZONE UNLOCK COSTS ===
    // gold = baseGold * exponent ^ zoneIdx
    unlockBaseGold: 1000,
    unlockGoldExponent: 5,
    // ore = baseOre * exponent ^ zoneIdx  (of the PREVIOUS zone)
    unlockBaseOre: 500,
    unlockOreExponent: 2.5,

    // === POWER-UPS ===
    powerUpSpawnIntervalMin: 180, // seconds
    powerUpSpawnIntervalMax: 300, // seconds
    powerUpDespawnTime: 15,       // seconds after which unclicked power-up disappears
    buffs: {
        sharpPick: {
            opcMultiplier: 5,
            durationSec: 30,
            label: "Sharp Pick",
            desc: "5x OPC for 30s"
        },
        merchantsFavor: {
            sellMultiplier: 2,
            durationSec: 10,
            label: "Merchant's Favor",
            desc: "2x Sell Value for 10s"
        },
        overdrive: {
            speedMultiplier: 2,
            durationSec: 300,
            label: "Overdrive",
            desc: "2x Auto-Miner Speed for 5m"
        }
    }
};
