// Card model and sprite-sheet geometry.
//
// Pure data: no DOM, no storage, no randomness, nothing executed at import time.
// That is what lets the test suite import this directly.

export type Suit = 'H' | 'D' | 'S' | 'C';

/** 2-10 face value, 11=J, 12=Q, 13=K, 14=A. Ace is high; the wheel (A-2-3-4-5)
 *  is handled as a special case in the evaluator rather than by storing A as 1. */
export type Rank = 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14;

export interface Card {
    readonly rank: Rank;
    readonly suit: Suit;
}

/** Exactly five cards. The tuple encodes the length in the type system and
 *  keeps `hand[0]` a `Card` rather than `Card | undefined` under
 *  noUncheckedIndexedAccess. */
export type Hand = readonly [Card, Card, Card, Card, Card];

export const SUITS: readonly Suit[] = ['H', 'D', 'S', 'C'];
export const RANKS: readonly Rank[] = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14];

export const JACK: Rank = 11;
export const QUEEN: Rank = 12;
export const KING: Rank = 13;
export const ACE: Rank = 14;
export const TEN: Rank = 10;

// --- Sprite sheet geometry -------------------------------------------------
//
// assets/cards.png is generated by scripts/build-casino-sprites.mjs. Each 48x64
// card sits inset 1px inside a 50x66 cell; the transparent gutter stops a
// fractional devicePixelRatio from sampling a sliver of the neighbouring card.
//
// Layout: 15 cols x 5 rows.
//   row 0  Hearts   A,2..10,J,Q,K  + red joker (13) + black joker (14)
//   row 1  Diamonds A..K
//   row 2  Spades   A..K
//   row 3  Clubs    A..K
//   row 4  8 card backs (cols 0-7)

export const CARD_W = 48;
export const CARD_H = 64;
export const CELL_W = 50;
export const CELL_H = 66;
export const CELL_INSET = 1;
export const SHEET_COLS = 15;
export const SHEET_ROWS = 5;
export const SHEET_W = SHEET_COLS * CELL_W; // 750
export const SHEET_H = SHEET_ROWS * CELL_H; // 330

const SUIT_ROW: Readonly<Record<Suit, number>> = { H: 0, D: 1, S: 2, C: 3 };

/** Column on the sheet. Ace lives at column 0, so it wraps rather than sorting
 *  to the far end. */
export function spriteCol(rank: Rank): number {
    return rank === ACE ? 0 : rank - 1;
}

export function spriteRow(suit: Suit): number {
    return SUIT_ROW[suit];
}

/** Canonical card back (row 4, col 4 — the blue one). */
export const CARD_BACK_COL = 4;
export const CARD_BACK_ROW = 4;

/** Top-left pixel of a cell's card content on the sheet, before scaling. */
export function spriteOffset(col: number, row: number): { x: number; y: number } {
    return { x: col * CELL_W + CELL_INSET, y: row * CELL_H + CELL_INSET };
}

// --- Naming ----------------------------------------------------------------

const RANK_NAMES: Readonly<Record<Rank, string>> = {
    2: 'Two', 3: 'Three', 4: 'Four', 5: 'Five', 6: 'Six', 7: 'Seven',
    8: 'Eight', 9: 'Nine', 10: 'Ten', 11: 'Jack', 12: 'Queen', 13: 'King', 14: 'Ace',
};

const SUIT_NAMES: Readonly<Record<Suit, string>> = {
    H: 'Hearts', D: 'Diamonds', S: 'Spades', C: 'Clubs',
};

const RANK_SHORT: Readonly<Record<Rank, string>> = {
    2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9',
    10: '10', 11: 'J', 12: 'Q', 13: 'K', 14: 'A',
};

const SUIT_SYMBOL: Readonly<Record<Suit, string>> = {
    H: '♥', D: '♦', S: '♠', C: '♣',
};

/** Screen-reader name, e.g. "Ace of Spades". */
export function cardLabel(card: Card): string {
    return `${RANK_NAMES[card.rank]} of ${SUIT_NAMES[card.suit]}`;
}

/** Compact name for logs and tests, e.g. "A♠". */
export function cardShort(card: Card): string {
    return `${RANK_SHORT[card.rank]}${SUIT_SYMBOL[card.suit]}`;
}

/** Stable identity for dedupe checks and serialisation. */
export function cardId(card: Card): string {
    return `${card.rank}${card.suit}`;
}
