// Card model and sprite-sheet geometry.
//
// Pure data: no DOM, no storage, no randomness, nothing executed at import time.
// That is what lets the test suite import this directly.
export const SUITS = ['H', 'D', 'S', 'C'];
export const RANKS = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14];
export const JACK = 11;
export const QUEEN = 12;
export const KING = 13;
export const ACE = 14;
export const TEN = 10;
// --- Sprite sheet geometry -------------------------------------------------
//
// assets/cards.png is generated by scripts/build-casino-sprites.mjs. Each 48x64
// card sits inset 1px inside a 50x66 cell; the transparent gutter stops a
// fractional devicePixelRatio from sampling a sliver of the neighbouring card.
//
// Layout: 15 cols x 5 rows.
//   row 0  Hearts   A,2..10,J,Q,K  + red joker (13) + black joker (14)
//   row 1  Diamonds A..K
//   row 2  Spades   A..K
//   row 3  Clubs    A..K
//   row 4  8 card backs (cols 0-7)
export const CARD_W = 48;
export const CARD_H = 64;
export const CELL_W = 50;
export const CELL_H = 66;
export const CELL_INSET = 1;
export const SHEET_COLS = 15;
export const SHEET_ROWS = 5;
export const SHEET_W = SHEET_COLS * CELL_W; // 750
export const SHEET_H = SHEET_ROWS * CELL_H; // 330
const SUIT_ROW = { H: 0, D: 1, S: 2, C: 3 };
/** Column on the sheet. Ace lives at column 0, so it wraps rather than sorting
 *  to the far end. */
export function spriteCol(rank) {
    return rank === ACE ? 0 : rank - 1;
}
export function spriteRow(suit) {
    return SUIT_ROW[suit];
}
/** Canonical card back (row 4, col 4 — the blue one). */
export const CARD_BACK_COL = 4;
export const CARD_BACK_ROW = 4;
/** Top-left pixel of a cell's card content on the sheet, before scaling. */
export function spriteOffset(col, row) {
    return { x: col * CELL_W + CELL_INSET, y: row * CELL_H + CELL_INSET };
}
// --- Naming ----------------------------------------------------------------
const RANK_NAMES = {
    2: 'Two', 3: 'Three', 4: 'Four', 5: 'Five', 6: 'Six', 7: 'Seven',
    8: 'Eight', 9: 'Nine', 10: 'Ten', 11: 'Jack', 12: 'Queen', 13: 'King', 14: 'Ace',
};
const SUIT_NAMES = {
    H: 'Hearts', D: 'Diamonds', S: 'Spades', C: 'Clubs',
};
const RANK_SHORT = {
    2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9',
    10: '10', 11: 'J', 12: 'Q', 13: 'K', 14: 'A',
};
const SUIT_SYMBOL = {
    H: '♥', D: '♦', S: '♠', C: '♣',
};
/** Screen-reader name, e.g. "Ace of Spades". */
export function cardLabel(card) {
    return `${RANK_NAMES[card.rank]} of ${SUIT_NAMES[card.suit]}`;
}
/** Compact name for logs and tests, e.g. "A♠". */
export function cardShort(card) {
    return `${RANK_SHORT[card.rank]}${SUIT_SYMBOL[card.suit]}`;
}
/** Stable identity for dedupe checks and serialisation. */
export function cardId(card) {
    return `${card.rank}${card.suit}`;
}
